extends Node
## Global signal hub — scenes subscribe; game logic emits.

signal swing_resolved(yards: float, timing_tier: int, payout: float, feedback_tier: int)
signal upgrade_purchased(id: String, level: int, branch: int)
signal shop_item_purchased(id: String, level: int)
signal stats_changed(stats: PlayerStats, currency: float)
signal currency_changed(currency: float)
signal milestone_reached(id: String, display_name: String)
signal swing_charging_changed(charging: bool)
signal swing_charge_updated(windup_progress: float, in_contact_band: bool, past_contact: bool)
signal ui_panel_toggled(panel_id: String, is_open: bool)
signal bucket_changed(count: int, capacity: int)
signal phase_changed(phase: String)
signal ball_collected(world_pos: Vector3, combo: int)
signal bucket_completed(bonus: float)
signal pickup_payout(amount: float, combo: int)
signal ratina_upgrade_purchased(id: String, level: int)
signal ratina_swing_resolved(yards: float, timing_tier: int, payout: float)
signal ratina_ball_collected(amount: float)
signal atmosphere_tint_changed(tint: Color)
signal rattling_upgrade_purchased(id: String, level: int)
signal rattling_ball_collected(amount: float)
signal helper_toggled(helper: String, active: bool)
signal cheese_changed(cheese: float)
signal prestiged(prestige_count: int, cheese_gained: float)
signal prestige_upgrade_purchased(id: String, level: int)
